// <auto-generated />
namespace pets.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class normalDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(normalDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201910271205574_normalDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
